[colors]
ansi = [
    "#black", # Black
    "#red", # Red
    "#green", # Green
    "#yellow", # Yellow
    "#blue", # Blue
    "#magenta", # Magenta
    "#cyan", # Cyan
    "#white", # White
]

brights = [
    "#bblack", # Black
    "#bred", # Red
    "#bgreen", # Green
    "#byellow", # Yellow
    "#bblue", # Blue
    "#bmagenta", # Magenta
    "#bcyan", # Cyan
    "#bwhite", # White
]

background = "#background"
foreground = "#foreground"

cursor_bg = "#foreground"
cursor_fg = "#background"
cursor_border = "#foreground"

scrollbar_thumb = "#black"

selection_bg = "#black"
selection_fg = "#foreground"

split = "#black"
visual_bell = "#black"

[colors.indexed]

[colors.tab_bar]
background = "#background"
inactive_tab_edge = "#background"

[colors.tab_bar.active_tab]
bg_color = "#background"
fg_color = "#foreground"

intensity = "Bold"      # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#background"
fg_color = "#bblack"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#background"
fg_color = "#foreground"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color = "#background"
fg_color = "#bblack"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color = "#background"
fg_color = "#foreground"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false
