[colors]
ansi = [
    "#101010", # Black
    "#cc5d4b", # Red
    "#2e9969", # Green
    "#b38d59", # Yellow
    "#6179c2", # Blue
    "#ab78ab", # Magenta
    "#33919c", # Cyan
    "#a5a5a5", # White
]

brights = [
    "#3d3d3d", # Black
    "#d96857", # Red
    "#66cc69", # Green
    "#cc9b52", # Yellow
    "#5582c2", # Blue
    "#bf86bf", # Magenta
    "#73bfbf", # Cyan
    "#cdcdcd", # White
]

background = "#0c0c0c"
foreground = "#f2e6cf"

cursor_bg = "#f2e6cf"
cursor_fg = "#0c0c0c"
cursor_border = "#f2e6cf"

scrollbar_thumb = "#101010"

selection_bg = "#101010"
selection_fg = "#f2e6cf"

split = "#101010"
visual_bell = "#101010"

[colors.indexed]

[colors.tab_bar]
background = "#0c0c0c"
inactive_tab_edge = "#0c0c0c"

[colors.tab_bar.active_tab]
bg_color = "#0c0c0c"
fg_color = "#f2e6cf"

intensity = "Bold"      # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#0c0c0c"
fg_color = "#3d3d3d"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#0c0c0c"
fg_color = "#f2e6cf"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = true
strikethrough = false

[colors.tab_bar.new_tab]
bg_color = "#0c0c0c"
fg_color = "#3d3d3d"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
bg_color = "#0c0c0c"
fg_color = "#f2e6cf"

intensity = "Normal"    # Half | Normal | Bold
underline = "None"      # None | Single | Double
italic = false
strikethrough = false
